# Generated by Django 4.2.3 on 2023-08-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('internalId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('externalId', models.IntegerField(unique=True)),
                ('customer', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('isDone', models.BooleanField(default=False)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('scheduledDate', models.DateField()),
                ('scheduledOrder', models.PositiveIntegerField()),
                ('driverEmail', models.EmailField(max_length=100)),
                ('driverNotes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='calls.call')),
            ],
        ),
    ]
