READ_MY_CALLS_PERMISSION = "read:my_calls"
UPDATE_MY_CALLS_PERMISSION = "update:my_calls"
ADD_MY_CALLS_PERMISSION = "add:my_calls"
READ_OTHER_CALLS_PERMISSION = "read:other_calls"
UPDATE_OTHER_CALLS_PERMISSION = "update:other_calls"
ADD_OTHER_CALLS_PERMISSION = "add:other_calls"
READ_USERS_PERMISSION = "read:users"
UPDATE_USERS_PERMISSION = "update:users"
ADD_USERS_PERMISSION = "add:users"
READ_SYSTEM_SETTINGS_PERMISSION = "read:settings"
UPDATE_SYSTEM_SETTINGS_PERMISSION = "update:settings"

ALL_PERMISSIONS = [
    READ_MY_CALLS_PERMISSION,
    UPDATE_MY_CALLS_PERMISSION,
    ADD_MY_CALLS_PERMISSION,
    READ_OTHER_CALLS_PERMISSION,
    UPDATE_OTHER_CALLS_PERMISSION,
    ADD_OTHER_CALLS_PERMISSION,
    READ_USERS_PERMISSION,
    UPDATE_USERS_PERMISSION,
    ADD_USERS_PERMISSION,
    READ_SYSTEM_SETTINGS_PERMISSION,
    UPDATE_SYSTEM_SETTINGS_PERMISSION,
]
