export const CALL_LIST_REQUEST = "CALL_LIST_REQUEST";
export const CALL_LIST_SUCCESS = "CALL_LIST_SUCCESS";
export const CALL_LIST_FAIL = "CALL_LIST_FAIL";

export const CALL_UPDATE_REQUEST = "CALL_UPDATE_REQUEST";
export const CALL_UPDATE_SUCCESS = "CALL_UPDATE_SUCCESS";
export const CALL_UPDATE_FAIL = "CALL_UPDATE_FAIL";

export const CALL_ADD_REQUEST = "CALL_ADD_REQUEST";
export const CALL_ADD_SUCCESS = "CALL_ADD_SUCCESS";
export const CALL_ADD_FAIL = "CALL_ADD_FAIL";

export const CALL_ADD_EXAMPLE_REQUEST = "CALL_ADD_EXAMPLE_REQUEST";
export const CALL_ADD_EXAMPLE_SUCCESS = "CALL_ADD_EXAMPLE_SUCCESS";
export const CALL_ADD_EXAMPLE_FAIL = "CALL_ADD_EXAMPLE_FAIL";
