export const SETTINGS_LIST_REQUEST = "SETTINGS_LIST_REQUEST";
export const SETTINGS_LIST_SUCCESS = "SETTINGS_LIST_SUCCESS";
export const SETTINGS_LIST_FAIL = "SETTINGS_LIST_FAIL";

export const SETTING_UPDATE_REQUEST = "SETTING_UPDATE_REQUEST";
export const SETTING_UPDATE_SUCCESS = "SETTING_UPDATE_SUCCESS";
export const SETTING_UPDATE_FAIL = "SETTING_UPDATE_FAIL";
