# Generated by Django 4.2.3 on 2023-08-08 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_temporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='added_at',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
