# Generated by Django 4.2.3 on 2023-08-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_added_at_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='scope_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='remote_user_id',
            new_name='auth0_user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='users.permission'),
        ),
    ]
